/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    BussLeft: typeof import('./src/components/bussLeft.vue')['default']
    BussTop: typeof import('./src/components/bussTop.vue')['default']
    DetailMain: typeof import('./src/components/detailMain.vue')['default']
    HomeLeft: typeof import('./src/components/homeLeft.vue')['default']
    HomeTop: typeof import('./src/components/homeTop.vue')['default']
    IndexBottom: typeof import('./src/components/indexBottom.vue')['default']
    IndexTop: typeof import('./src/components/indexTop.vue')['default']
    ObjectEdit: typeof import('./src/components/objectEdit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopLeft: typeof import('./src/components/shopLeft.vue')['default']
    UserEdit: typeof import('./src/components/userEdit.vue')['default']
  }
}
